#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

rm -fR '/var/tmp/rad'
mkdir -p '/var/tmp/rad'

for pkg in \
fs \
core \
linux-headers \
musl \
perl \
automake \
bash \
byacc \
curl \
cmake \
gperf \
libcap \
libressl \
shadow \
bzip2 \
pigz \
libarchive \
lz4 \
xz \
zlib-ng \
zstd \
autoconf \
expat \
file \
flex \
gettext-tiny \
libedit \
m4 \
make \
muon \
netbsd-curses \
pcre2 \
slibtool \
u-config \
eiwd \
fping \
iproute2 \
openresolv \
sdhcp \
dash \
hwdata \
kmod \
less \
libudev-zero \
neatvi \
pciutils \
toybox \
util-linux \
xxhash \
yash \
skalibs \
execline \
mdevd \
s6 \
utmps \
s6-linux-init \
s6-rc \
s6-boot-scripts \
linux-cachyos; do
done

printf -- '%s\n' 'stage 3 (native) bootstrap complete'
