#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

CFLAGS="-O2 -fstack-protector-strong -fstack-clash-protection -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-plt"
LDFLAGS="-Wl,-O1,-s,-z,noexecstack,-z,now,-z,pack-relative-relocs,-z,relro,--as-needed,--gc-sections,--sort-common,--hash-style=gnu -Wno-stringop-overflow"

mkdir -p \
  ../src/nim \
  ../tmp/nim \
  ../toolchain

curl -fL --output-dir ../src/nim -Os https://github.com/nim-lang/Nim/archive/v2.2.6.tar.gz

tar --no-same-owner -xmP -f ../src/nim/v2.2.6.tar.gz -C ../tmp/nim

git clone https://github.com/nim-lang/csources_v3 ../tmp/nim/Nim-2.2.6/csources_v3 -q

git -C ../tmp/nim/Nim-2.2.6/csources_v3 checkout eeab3ac -q

cd ../tmp/nim/Nim-2.2.6/csources_v3

LDFLAGS="$LDFLAGS" \
sh build.sh \
  --os Linux \
  --cpu amd64 \
  --extraBuildArgs "$CFLAGS" \
  --parallel 5

cd ..

./bin/nim compile \
  -d:release \
  -d:strip \
  --hints:off \
  --os:linux \
  --cpu:amd64 \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath \
  koch

./koch boot \
  -d:release \
  -d:leanCompiler

./deinstall.sh /usr/bin

DESTDIR=../toolchain \
./install.sh \
  /usr/bin

echo "bootstrap nim complete"
