#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

cd ..

mkdir -p \
  /var/cache/rad \
  /var/lib/rad/repo

ln -fs $PWD/core /var/lib/rad/repo
ln -fs $PWD/log /var/log/rad
ln -fs $PWD/src /var/cache/rad
ln -fs $PWD/tmp /var/tmp/rad

for i in \
a2x asciidoc \
gtkdocize \
help2man \
ldconfig \
makeinfo \
po4a \
texi2dvi texi2pdf \
yodl2man; do
  cp -fPp core/musl/files/true /usr/bin/$i
done

cd live

./bootstrap-nim

PATH="../toolchain/lib/nim/bin:$PATH" \
./nim \
  -o:../rad/rad \
  ../rad/src/rad.nim

cd ../rad

./rad bootstrap 1
./rad bootstrap 2

cd ../live

./img

./nim \
  -o:../rad/rad-x86-64-v3-glaucus-linux-musl \
  --gcc.exe:../toolchain/usr/bin/x86_64-glaucus-linux-musl-gcc \
  --gcc.linkerexe:../toolchain/usr/bin/x86_64-glaucus-linux-musl-gcc \
  ../rad/src/rad.nim

./mount
./umount

echo "bootstrap complete"
