#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -efu

glaucus="$(cd "$(dirname "$0")"/.. && pwd -P)"

. "$glaucus/core/nim/info"

CFLAGS='-pipe -Os -fgcse-las -flto=auto -fuse-linker-plugin -ffunction-sections -fdata-sections -fstack-protector-strong -fstack-clash-protection -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident -fno-plt -march=x86-64-v3 -mtls-dialect=gnu2'
LDFLAGS="-Wl,-O1,-s,-z,defs,-z,noexecstack,-z,now,-z,pack-relative-relocs,-z,relro,-z,separate-code,-z,text,--as-needed,--gc-sections,--no-keep-memory,--relax,--sort-common,--enable-new-dtags,--hash-style=gnu,--build-id=none -Wno-stringop-overflow -Wno-stringop-overread $CFLAGS"

src='/var/cache/rad/src/nim'
tmp='/var/tmp/rad/nim'

rm -fR \
  "$src" \
  "$tmp"

mkdir -p \
  "$src" \
  "$tmp" \
  "$glaucus/toolchain/bin"

curl -fL --output-dir "$src" -Os "$url"

tar --no-same-owner -xmP -f "$src/v$ver.tar.gz" -C "$tmp"

git clone https://github.com/nim-lang/csources_v3 "$tmp/Nim-$ver/csources_v3" -q

git -C "$tmp/Nim-$ver/csources_v3" checkout eeab3ac -q

cd "$tmp/Nim-$ver/csources_v3"

make \
  CFLAGS="-Ic_code -w -fmax-errors=3 -fno-strict-aliasing -fno-ident -fno-math-errno $CFLAGS" \
  LDFLAGS="-ldl -lm -lrt $LDFLAGS" \
  -j 5 -O

cd ..

bin/nim compile \
  -d:release \
  -d:useMalloc \
  -d:strip \
  --os:linux \
  --cpu:amd64 \
  --passC:"$CFLAGS" \
  --passL:"$LDFLAGS" \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath \
  koch

./koch boot \
  -d:release \
  -d:leanCompiler \
  -d:useMalloc \
  -d:strip \
  --os:linux \
  --cpu:amd64 \
  --passC:"$CFLAGS" \
  --passL:"$LDFLAGS" \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath

./koch install \
  "$glaucus/toolchain/lib"

ln -fs ../lib/nim/bin/nim "$glaucus/toolchain/bin"

echo "bootstrap nim complete"
