#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

glaucus="$(cd "$(dirname "$0")"/.. && pwd -P)"

: "${glaucus:?}"

rm -fR "$glaucus/tmp"

mkdir -p "$glaucus/tmp"

export PATH="$glaucus/toolchain/bin:$PATH"

export CROSS_COMPILE="x86_64-glaucus-linux-musl-"

export PKG_CONFIG_LIBDIR="$glaucus/cross/usr/lib/pkgconfig"
export PKG_CONFIG_PATH="$glaucus/cross/usr/lib/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="$glaucus/cross/"
export PKG_CONFIG_SYSTEM_INCLUDE_PATH="$glaucus/cross/usr/include"
export PKG_CONFIG_SYSTEM_LIBRARY_PATH="$glaucus/cross/usr/lib"

. "$glaucus/core/cross/info"

# Set `bootstrap` to yes, and stage to `cross`
# ./rad build "$run"
# ./img

printf -- '%s\n' 'bootstrap cross complete'
