#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

for i in \
autoconf automake autopoint awk \
bash booster bzip2 \
clang clang++ curl \
diff \
find flex \
git gperf grep gzip \
ld.lld libtool limine \
m4 make meson mkfs.erofs mkfs.fat \
ninja \
patch perl pkg-config \
sed \
tar \
xxhsum xz \
yacc \
zstd; do
  if ! command -v "$i" > /dev/null 2>&1; then
    printf -- '%s\n' "$i not found"
    exit 127
  fi
done

glaucus="$(cd "$(dirname "$0")"/.. && pwd -P)"

: "${glaucus:?}"

rm -fRv \
  "$glaucus/cross" \
  "$glaucus/log" \
  "$glaucus/tmp" \
  "$glaucus/toolchain"

mkdir -p \
  "$glaucus/cross" \
  "$glaucus/log" \
  "$glaucus/pkg" \
  "$glaucus/src/nim" \
  "$glaucus/tmp/nim" \
  "$glaucus/toolchain/bin"

for i in \
a2x asciidoc \
gtkdocize \
help2man \
ldconfig \
makeinfo \
po4a \
texi2dvi texi2html texi2pdf \
yodl2man; do
  cp -fPp "$glaucus/core/musl/files/true" "$glaucus/toolchain/bin/$i"
done

cp -fPp \
  "$glaucus/core/autoconf/files/glaucus-configure" \
  "$glaucus/core/cmake/files/glaucus-cmake" \
  "$glaucus/core/muon/files/glaucus-meson" \
  "$glaucus/core/muon/files/glaucus-muon" \
  "$glaucus/core/nim/files/glaucus-nim" \
  "$glaucus/toolchain/bin"

. "$glaucus/core/nim/info"

nim="$glaucus/src/nim/$(basename "$url")"

if [ ! -f "$nim" ] || [ "$(xxhsum -H2 "$nim" | cut -d ' ' -f 1)" != "$sum" ]; then
  curl -fL --output-dir "$glaucus/src/nim" -O "$url"
fi

tar --no-same-owner -xmP -f "$nim" -C "$glaucus/tmp/nim"

if [ ! -d "$glaucus/src/nim/csources_v3" ]; then
  git clone https://github.com/nim-lang/csources_v3 "$glaucus/src/nim"
fi

git -C "$glaucus/src/nim/csources_v3" checkout eeab3ac

cp -fPpR "$glaucus/src/nim/csources_v3" "$glaucus/tmp/nim/Nim-$ver"

cd "$glaucus/tmp/nim/Nim-$ver/csources_v3"

CFLAGS='-pipe -Os -fgcse-las -flto=auto -fuse-linker-plugin -ffunction-sections -fdata-sections -fstack-protector-strong -fstack-clash-protection -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident -fno-plt -march=x86-64-v3 -mtls-dialect=gnu2'
LDFLAGS="-Wl,-O1,-s,-z,defs,-z,noexecstack,-z,now,-z,pack-relative-relocs,-z,relro,-z,separate-code,-z,text,--as-needed,--gc-sections,--no-keep-memory,--relax,--sort-common,--enable-new-dtags,--hash-style=gnu,--build-id=none -Wno-stringop-overflow -Wno-stringop-overread $CFLAGS"

make \
  CFLAGS="-Ic_code -w -fmax-errors=3 -fno-strict-aliasing -fno-ident -fno-math-errno $CFLAGS" \
  LDFLAGS="-ldl -lm -lrt $LDFLAGS" \
  -j 5 -O

cd "$glaucus/tmp/nim/Nim-$ver"

bin/nim compile \
  -d:release \
  -d:useMalloc \
  -d:strip \
  --os:linux \
  --cpu:amd64 \
  --passC:"$CFLAGS" \
  --passL:"$LDFLAGS" \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath \
  koch

./koch boot \
  -d:release \
  -d:leanCompiler \
  -d:useMalloc \
  -d:strip \
  --os:linux \
  --cpu:amd64 \
  --passC:"$CFLAGS" \
  --passL:"$LDFLAGS" \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath

./koch install "$glaucus/toolchain/lib"

ln -fs ../lib/nim/bin/nim "$glaucus/toolchain/bin"

export PATH="$glaucus/toolchain/bin:$PATH"

glaucus-nim -o:"$glaucus/toolchain/bin/rad" "$glaucus/rad/src/rad.nim"

cd "$glaucus/rad"

. "$glaucus/core/toolchain/info"

# Set `bootstrap` to yes, and stage to `toolchain`
# ./rad build "$run"

printf -- '%s\n' 'bootstrap toolchain complete'
