#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

ver=2.2.6

CFLAGS="-pipe -Os -fgcse-las -flto=auto -fuse-linker-plugin -ffunction-sections -fdata-sections -fstack-protector-strong -fstack-clash-protection -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident -fno-plt -march=x86-64-v3 -mtls-dialect=gnu2"
LDFLAGS="-Wl,-O1,-s,-z,defs,-z,noexecstack,-z,now,-z,pack-relative-relocs,-z,relro,-z,separate-code,-z,text,--as-needed,--gc-sections,--no-keep-memory,--relax,--sort-common,--enable-new-dtags,--hash-style=gnu,--build-id=none -Wno-stringop-overflow -Wno-stringop-overread -pipe -Os -fgcse-las -flto=auto -fuse-linker-plugin -ffunction-sections -fdata-sections -fstack-protector-strong -fstack-clash-protection -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-ident -fno-plt -march=x86-64-v3 -mtls-dialect=gnu2"

mkdir -p \
  ../src/nim \
  ../tmp/nim \
  ../toolchain

curl -fL --output-dir ../src/nim -Os https://github.com/nim-lang/Nim/archive/v$ver.tar.gz

tar --no-same-owner -xmP -f ../src/nim/v$ver.tar.gz -C ../tmp/nim

git clone https://github.com/nim-lang/csources_v3 ../tmp/nim/Nim-$ver/csources_v3 -q

git -C ../tmp/nim/Nim-$ver/csources_v3 checkout eeab3ac -q

cd ../tmp/nim/Nim-$ver/csources_v3

make \
  CFLAGS="-Ic_code -w -fmax-errors=3 -fno-strict-aliasing -fno-ident -fno-math-errno $CFLAGS" \
  LDFLAGS="-ldl -lm -lrt $LDFLAGS" \
  -j 5 -O

cd ..

bin/nim compile \
  -d:release \
  -d:useMalloc \
  -d:strip \
  --os:linux \
  --cpu:amd64 \
  --passC:"$CFLAGS" \
  --passL:"$LDFLAGS" \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath \
  koch

./koch boot \
  -d:release \
  -d:leanCompiler \
  -d:useMalloc \
  -d:strip \
  --os:linux \
  --cpu:amd64 \
  --passC:"$CFLAGS" \
  --passL:"$LDFLAGS" \
  --skipUserCfg \
  --skipParentCfg \
  --noNimblePath

./koch install \
  ../../../toolchain/lib

ln -fs ../lib/nim/bin/nim ../../../toolchain/bin

echo "bootstrap nim complete"
