#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2018-2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

glaucus="$(cd "$(dirname "$0")/.." && pwd -P)"
: "${glaucus:?}"

cross="$glaucus/cross"

mountpoint -q "$cross/dev" && umount -fR "$cross/dev"
mountpoint -q "$cross/proc" && umount -fR "$cross/proc"
mountpoint -q "$cross/sys" && umount -fR "$cross/sys"

chown -R root:root "$cross"

mount -B /dev "$cross/dev"
mount -t proc proc "$cross/proc"
mount -t sysfs sys "$cross/sys"

chroot "$cross" \
  env -i \
  HOME=/root \
  PATH=/usr/bin \
  TERM="$TERM" \
  yash
