#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

ver="$(uname -r)"

core='/var/lib/rad/repo/core'
gen='../gen'
mod="/usr/lib/modules/$ver/kernel"

rm -fR \
  "$gen" \
  ../initramfs

mkdir -p "$gen"
cd "$gen"

mkdir -p \
  dev \
  etc \
  media/fs-ro \
  media/fs-rw \
  media/iso \
  mnt/root \
  run \
  usr/bin \
  usr/lib/modules/$ver/kernel/drivers/usb

mkdir -m 555 -p \
  proc \
  sys

ln -fs usr/bin bin
ln -fs usr/lib lib
ln -fs usr/bin sbin
ln -fs bin usr/sbin

cp -fPp ../live/init .

cp -fPp \
  "$core"/fs/files/group \
  "$core"/fs/files/passwd \
  "$core"/mdevd/files/mdev.conf \
  etc

cp -fPp \
  /usr/bin/blkid \
  /usr/bin/dash \
  /usr/bin/kill \
  /usr/bin/kmod \
  /usr/bin/mdevd \
  /usr/bin/mdevd-coldplug \
  /usr/bin/mount \
  /usr/bin/switch_root \
  /usr/bin/toybox \
  usr/bin

ln -fs dash usr/bin/sh
ln -fs kmod usr/bin/modprobe

for i in "$(toybox)"; do
  ln -fs toybox usr/bin/$i
done

cp -fPp \
  /usr/lib/ld-musl-x86_64.so.1 \
  /usr/lib/libblkid.so* \
  /usr/lib/libc.so \
  /usr/lib/libcrypto.so* \
  /usr/lib/libedit.so* \
  /usr/lib/liblzma.so* \
  /usr/lib/libmount.so* \
  /usr/lib/libskarnet.so* \
  /usr/lib/libterminfo.so \
  /usr/lib/libutmps.so* \
  /usr/lib/libz.so* \
  /usr/lib/libzstd.so* \
  usr/lib

cp -fPpR \
  "$mod"/arch \
  "$mod"/crypto \
  "$mod"/fs \
  "$mod"/lib \
  usr/lib/modules/"$ver"/kernel

cp -fPpR \
  "$mod"/drivers/ata \
  "$mod"/drivers/block \
  "$mod"/drivers/cdrom \
  "$mod"/drivers/gpu \
  "$mod"/drivers/hid \
  "$mod"/drivers/hwmon \
  "$mod"/drivers/input \
  "$mod"/drivers/md \
  "$mod"/drivers/message \
  "$mod"/drivers/nvme \
  "$mod"/drivers/scsi \
  "$mod"/drivers/usb/host \
  "$mod"/drivers/usb/storage \
  "$mod"/drivers/virtio \
  usr/lib/modules/"$ver"/kernel/drivers

cp -fPp \
  "$mod"/../modules.builtin \
  "$mod"/../modules.builtin.modinfo \
  "$mod"/../modules.order \
  usr/lib/modules/"$ver"

depmod -b . "$ver"

find . | cpio -o | zstd -3 -T0 > ../initramfs

cd ../live

rm -fR "$gen"

echo "gen complete"
