#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

curl -fL --output-dir ~ -JOs https://github.com/nim-lang/nightlies/releases/download/latest-devel/linux_x64.tar.xz

tar --no-same-owner -xmP -f ~/linux_x64.tar.xz -C ~

~/nim-*/deinstall.sh /usr/bin

mv ~/nim-* ~/.nim

echo "install nim complete"
