#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

iso=../iso
pkg=../pkg/skel
ver=6.18.3-2-cachyos

rm -fR $iso

mkdir -p \
  $iso/EFI/BOOT \
  $iso/limine \
  $iso/tmp

cp -fPp \
  ../initramfs \
  ../cross/boot/vmlinuz \
  $iso

cp -fPp /usr/share/limine/BOOTX64.EFI $iso/EFI/BOOT
cp -fPp \
  ../core/limine/files/limine.conf \
  /usr/share/limine/limine-bios.sys \
  /usr/share/limine/limine-bios-cd.bin \
  /usr/share/limine/limine-uefi-cd.bin \
  $iso/limine

for i in $(ls $pkg); do
  tar --no-same-owner -xmP -f $pkg/$i/*.tar.zst -C $iso/tmp
done
for i in $(ls $pkg-devel); do
  tar --no-same-owner -xmP -f $pkg-devel/$i/*.tar.zst -C $iso/tmp
done
for i in $(ls $pkg-iso); do
  tar --no-same-owner -xmP -f $pkg-iso/$i/*.tar.zst -C $iso/tmp
done

mkdir -p \
  $iso/tmp/mnt/fs-ro \
  $iso/tmp/mnt/fs-rw \
  $iso/tmp/mnt/iso

cp -fPp ../rad/src/rad $iso/tmp/usr/bin

rm -fR \
  $iso/tmp/boot \
  $iso/tmp/usr/share/bash-completion \
  $iso/tmp/usr/share/doc \
  $iso/tmp/usr/share/info \
  $iso/tmp/usr/share/locale \
  $iso/tmp/usr/share/man

depmod -b $iso/tmp $ver

chown -R root:root $iso
chown -R 15:15 $iso/tmp/var/log/wtmpd

mkfs.erofs $iso/fs $iso/tmp

rm -fR $iso/tmp

xorriso \
  -as mkisofs \
  -o glaucus-s6-x86-64-v3.iso \
  -iso-level 3 \
  -l \
  -r \
  -J \
  -joliet-long \
  -hfsplus \
  -apm-block-size 2048 \
  -V GLAUCUS \
  -P glaucus \
  -A glaucus \
  -p glaucus \
  -b limine/limine-bios-cd.bin \
  -boot-load-size 4 \
  -no-emul-boot \
  -boot-info-table \
  --efi-boot limine/limine-uefi-cd.bin \
  --protective-msdos-label \
  -efi-boot-part \
  --efi-boot-image \
  $iso

limine bios-install $iso

rm -fR $iso

echo "iso complete"
