#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

img="${1:-../glaucus-s6-x86-64-v3.img}"
mnt=../mnt

if [ ! -f $img ]; then
  echo "img not found"
  exit 1
fi

modprobe loop

mountpoint -q $mnt && umount -fR $mnt
losetup -D

device=$(losetup -f)
partitionOne=${device}p1
partitionTwo=${device}p2

losetup $device $img
partx -a $device

rm -fR $mnt
mkdir -p $mnt

mount $partitionTwo $mnt
mount $partitionOne $mnt/boot

rm -fR $mnt/live
cp -fPpR ../live $mnt

[ -f $mnt/initramfs ] && cp -fPp $mnt/initramfs ..

cp -fPp ../rad/rad-x86-64-v3-glaucus-linux-musl $mnt/usr/bin/rad

chown -R 0:0 \
  $mnt/live \
  $mnt/usr/bin/rad

echo "mount complete"
