#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2026 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

mnt=../mnt

mountpoint -q $mnt && umount -fR $mnt
losetup -D

sleep 1

rm -fR $mnt

echo "umount complete"
